name: Documentation

on:
    push:
        paths-ignore:
            - "docs/**"
            - "docs_preparation/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry==1.4.2
                  poetry install --with=docs
            - name: Build documentation
              run: |
                poetry run sphinx-apidoc -o docs/reference cc_tk
            - name: Commit generated documentation
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Automatic documentation build
