name: Publish

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tags like 'v1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Generate documentation
      run: poetry run sphinx-build docs build

    - name: Build and publish package
      run: |
        poetry build
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish
