name: Validation

on: [push, pull_request]

jobs:
    validation:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11"]

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
                python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install

        - name: Run pytest
          run: |
                poetry install --with test
                poetry run pytest

        - name: Run pylint
          run: |
                poetry install --with lint
                poetry run pylint your_package_name
